### ISSUE TITLE
about output channel and label

### ISSUE THREAD

**Issue by Devil-Ideal** [Ziyan-Huang/STU-Net#13]
Hi ! I'm interesting in your excelent work. In STU-Net, the final 1×1×1 convolution layer for segmentation output has 105 channels, but the TotalSegmentator dataset  contains 104 anatomical structures (104 classes), So is there a channel that contains a segmentation mask for all foreground ?

**Comment by Ziyan-Huang** [comment]
Hi @Devil-Ideal,

Thank you for your interest in our work.

You're correct in observing that the final 1x1x1 convolution layer in our STU-Net model has 105 channels, while the TotalSegmentator dataset contains 104 anatomical structures. The extra channel is indeed designated for the "background" class.

In multi-class segmentation tasks like this, it's common to include an additional class for pixels or voxels that don't belong to any of the anatomical structures we're interested in segmenting. This allows the model to better differentiate between the target structures and everything else in the image.

**Comment by Devil-Ideal** [comment]
> Hi @Devil-Ideal,
> 
> Thank you for your interest in our work.
> 
> You're correct in observing that the final 1x1x1 convolution layer in our STU-Net model has 105 channels, while the TotalSegmentator dataset contains 104 anatomical structures. The extra channel is indeed designated for the "background" class.
> 
> In multi-class segmentation tasks like this, it's common to include an additional class for pixels or voxels that don't belong to any of the anatomical structures we're interested in segmenting. This allows the model to better differentiate between the target structures and everything else in the image.

thank you for your prompt reply !
