### ISSUE TITLE
Could not find trainer class

### ISSUE THREAD

**Issue by zhi-xuan-chen** [Ziyan-Huang/STU-Net#8]
I have put your files into the specific folder of nnunet, but I got this error ` raise RuntimeError("Could not find trainer class in nnunet.training.network_training")
RuntimeError: Could not find trainer class in nnunet.training.network_training`. It seems program can not find the trainer class, how can I do?

**Comment by Ziyan-Huang** [comment]
There may be several potential causes for the error. To investigate further, we recommend creating a new custom trainer that inherits from `nnUNetTrainerV2 `and incorporates minor modifications, such as adjusting the learning rate. This approach will assist in determining whether the issue originates from the trainer class or is a result of your particular setup.

**Comment by zhi-xuan-chen** [comment]
I find my program can work if I set the trainer as "nnUNetTrainerV2". BUT actually the `nnUNetTrainerV2.py` and `STUNetTrainer.py` are under the same content.

**Comment by zhi-xuan-chen** [comment]
Thank you for your answer. I have found the problem. The `STUNetTrainer.py` should be placed into the path of nnUNet package, not my nnUNet folder cloned from the nnUNet.
